GET http://localhost:3000/analytics/dotnet HTTP/1.1

####
POST http://localhost:4000/analytics HTTP/1.1
Content-Type: application/json
Authorization: Bearer <...>
{  "date": "2025-05-20",
  "users": 50,
  "revenue": 100,
  "session_duration": 250,
  "active_users": 300,
  "conversion_rate": 4,
  "revenue_growth": 7
}
####
POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "test123@gmail.com",
  "password" : "123456"
}

####
GET http://localhost:3000/analytics HTTP/1.1
Authorization: Bearer <...>

###
POST http://localhost:3000/analytics
Content-Type: application/json
Authorization: Bearer <...>
{  
  "date": "2025-03-27",
  "users": 301,
  "revenue": 1100,
  "session_duration": 80,
  "active_users": 150,
  "revenue_growth": 9,
  "conversion_rate": 5.3
}

#### Akun A 
POST http://localhost:3000/analytics
Authorization: Bearer <...>
-Type: application/json

{
  "users": 300,
  "revenue": 3000,
  "date": "2025-03-30",
  "session_duration": 30,
  "active_users": 30,
  "conversion_rate": 0.3,
  "revenue_growth": 0.15
}



# testing from Github
###
POST http://localhost:3000/analytics
Authorization: Bearer <...>
Content-Type: application/json

{
  "date": "2025-04-30",
  "users": 100,
  "revenue": 5000,
  "session_duration": 15,
  "active_users": 90,
  "conversion_rate": 0.4,
  "revenue_growth": 0.1
}


### PATCH - Edit Analytics
PATCH http://localhost:3000/analytics/66
Authorization: Bearer <...>
-Type: application/json

{
  "users": 150,
  "revenue": 8000
}

### 
GET http://localhost:3000/analytics HTTP/1.1
Authorization: Bearer ..--

#### user
DELETE http://localhost:3000/analytics/66 HTTP/1.1
Authorization: Bearer ..-
#### admin
DELETE http://localhost:3000/analytics/67 HTTP/1.1
Authorization: Bearer <...>

#### me
GET http://localhost:3000/auth/me HTTP/1.1
Authorization: Bearer <...>

####
GET http://localhost:4000/analytics/insight?from=2025-05-01&to=2025-05-31 HTTP/1.1
Authorization: Bearer <...>

####
GET http://localhost:4000/blog/list HTTP/1.1

####
GET http://localhost:4000/blog/testing-slug HTTP/1.1

####
POST http://localhost:4000/blog/create HTTP/1.1
Content-Type: application/json

{
  "title": "Artikel Pertama",
  "slug": "artikel-pertama",
  "author": "Nur Esa",
  "excerpt": "Ringkasan singkat isi artikel",
  "coverImage": "https://picsum.photos/seed/picsum/600/400",
  "tags": ["typescript", "sanity", "nestjs"]
}